# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger: none
pr: none

schedules:
  - cron: "0 */4 * * 1-5"
    displayName: Every 4 hours Mon-Fri
    branches:
      include:
        - master
    always: true

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'
  NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages
  disable.coverage.autogenerate: 'true'

steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk'
    inputs:
      packageType: sdk
      version: '7.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'

  - task: DotNetCoreCLI@2
    displayName: "Build"
    inputs:
      command: build
      projects: "ContosoUniversity.Api/*.csproj"
      arguments: '--configuration $(BuildConfiguration) -p:DeployOnBuild=true;WebPublishMethod=Package;PackageAsSingleFile=true;SkipInvalidConfigurations=true;DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip"'

  - task: DotNetCoreCLI@2
    displayName: dotnet test
    inputs:
      command: test
      arguments: '--no-restore --configuration $(BuildConfiguration) --verbosity normal --settings coverlet.runsettings --collect:"XPlat Code Coverage"'
      projects: |
        tests/**/*.UnitTests.csproj
        tests/**/*.IntegrationTests.csproj
        tests/**/*.FunctionalTests.csproj
      nobuild: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'

  - script: 'dotnet tool install --global dotnet-reportgenerator-globaltool --version 4.8.4'  
    displayName: 'Install ReportGenerator tool'

  - script: 'reportgenerator -reports:$(Agent.TempDirectory)/**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/CodeCoverage -reporttypes:"HtmlInline_AzurePipelines;Cobertura"'  
    displayName: 'Create code coverage reports'
